rootProject.name = "leetcode"
include("array")
include("linkedlist")
include("string")
include("hashtable")
include("queueAstack")
include("heap")
include("binarysearch")
include("recursive")
include("queueAstack:binarytree")
include("binarytree")
include("datastructure")
include("binarysearchtree")
include("narytree")
